name: Творческая мастерская "Точка сборки 3D"
title: Творческая мастерская "Точка сборки 3D"
author: Михаил Долгих
title-img: /projects/brand/logo-header.png
theme: minima
header_pages:
  - about.md
  - portfolio.md