var examplesList = {
   start: "Стартовый пример",
   lesson01vector: "Урок 01: Векторы",
   lesson02circle: "Урок 02: Окружности",
   lesson03arc: "Урок 03: Дуги",
   lesson04triangle: "Урок 04: Треугольники",
   lesson05box: "Урок 05: Параллепипед",
   lesson06sphere: "Урок 06: Сфера",
   lesson07cylinder: "Урок 07: Цилиндр и конус",
   lesson08torus: "Урок 08: Тор",
   lesson09coord: "Урок 09: Система координат",
   lesson10message: "Урок 10: Комментарии", 
   lesson11color: "Урок 11: Цвета",
   lesson12transparent: "Урок 12: Прозрачность",
   lesson13mark: "Урок 13: Метки отрезков и углов",
   lesson14frames: "Урок 14: Последовательные построения",
   lesson15trig: "Урок 15: Тригонометрические функции",
   lesson16power: "Урок 16: Степенные функции",
   lesson17minmax: "Урок 17: Функции Min, Max",
   lesson18random: "Урок 18: Функция Random",
   demo01cube: "Демо 01: Куб",
   demo02gyper: "Демо 02: Гиперплоскость",
   demo03dnk: "Демо 03: ДНК",
   demo04grap: "Демо 04: График"
}